version: "3"
services:
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html
networks:
  internal:
    driver: bridge